add index.html
ok-technopolis-autumn-2019/Stas_Milke pull request #1
Opened 2019-10-09 01:01 UTC by stasmilke

2019-10-09 05:31 UTC, fromanywhere requested changes

2019-10-09 05:31 UTC, fromanywhere commented on index.html
> +    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
Не используйте эту прагму, так как она устарела. Используйте charset атрибут <meta> элемента вместо этого. (https://developer.mozilla.org/ru/docs/web/html/element/meta)

2019-10-09 05:31 UTC, fromanywhere commented on index.html
> +              <input
В чем идея использовать input[type="image"]?

2019-10-09 05:31 UTC, fromanywhere commented on index.html
> +          <message class="todos-panel-actions-message">3 items left</message>
A valid custom element name is a sequence of characters name that meets all of the following requirements: name must match the PotentialCustomElementName production:

PotentialCustomElementName ::=
[a-z] (PCENChar)* '-' (PCENChar)*
PCENChar ::=
"-" | "." | [0-9] | "_" | [a-z] | #xB7 | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x203F-#x2040] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]

(http://w3c.github.io/webcomponents/spec/custom/#dfn-custom-element-type)

2019-10-09 05:31 UTC, fromanywhere commented on index.html
> +        <section class="todos-panel-actions">
Здесь проблемы со структурой — все элементы сейчас лежат плоским списком, хотя как минимум следовало бы выделить компонент фильтра

2019-10-09 13:42 UTC, stasmilke commented on index.html
> +              <input
Для создания кнопки в виде изображения. Но, как я понял после более глубокого прочтения документации, это не лучший способ в данном случае.

2019-10-11 08:56 UTC, fromanywhere commented on index.html
> +              <div>
Здесь конечно классов на элементе не хватает

2019-10-11 08:57 UTC, fromanywhere approved these changes

2019-10-14 16:46 UTC, merged