Added css
ok-technopolis-autumn-2019/Stas_Milke pull request #2
Opened 2019-10-14 22:32 UTC by stasmilke

2019-10-15 08:54 UTC, fromanywhere requested changes

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +div, section {
Так широко класть стили опасно. Лучше точечно, иначе потом переопределять обратно будет сложнее

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +    width: 100%;
ширина у них и так будет по браузеру, а вот сбросить margin и padding будет правильно

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +    justify-content: center;
Видимо это была попытка выровнять всё по центру страницы, включая вертикаль, но не получилось. Почему не получилось — потому что контейнер не растянулся, потому что родителям высота не задана. Ну или здесь просто лишнее свойство. Я бы не выравнивал по центру по высоте сейчас

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +    background: url(checkall.svg);
Хорошо!

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +    flex-direction: row;
оно по умолчанию row

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +    display: none;
Фокус с клавиатуры перестал работать. Как чинить: пофантазировать с альтернативным скрытием по принципу маски. visibility и opacity не подойдут, а вот что-нибудь про overflow: hidden или clip — вполне

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +.todos-panel__checkbox-base:hover + span {
опасно вешать селектор по тегу, лучше по классу

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +    opacity: 100;
не, это так не работает, у него диапазон 0–1, а здесь просто невалидное значение

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +    border: none
;

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +}
а :focus? оно не прорисовано, это подводный камень на ux

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +    border: 1px solid #EBDFDF;
А «прыгают» же немного по горизонтали при переключении. Это можно решать по-разному

2019-10-15 08:54 UTC, fromanywhere commented on style.css
> +
неплохой старт. Отдельный плюс — за широкие области у интерактивных элементов. Основной минус — фокусы с клавиатуры потерялись. В разработке важно не сломать то, что уже было сделано на предыдущем этапе

2019-10-16 01:19 UTC, stasmilke commented
В этом коммите еще не все исправил.

2019-10-20 22:38 UTC, fromanywhere requested changes

2019-10-20 22:38 UTC, fromanywhere commented on style.css
> +    letter-spacing: -0.6px;
Не нужно этого

2019-10-20 22:38 UTC, fromanywhere commented on style.css
> +    font-family: Roboto;
Сам шрифт-то подключить нужно, fonts.google.com

2019-10-20 22:38 UTC, fromanywhere commented on style.css
> +    letter-spacing: -0.6px;
Тут всё не очень 
![image](https://user-images.githubusercontent.com/1042969/67167458-e85a6300-f3a2-11e9-9cb2-7c5f12b15cc6.png)

2019-10-20 22:38 UTC, fromanywhere commented on style.css
> +    letter-spacing: -0.6px;
даже с принудительным переносом не очень 
![image](https://user-images.githubusercontent.com/1042969/67167471-fdcf8d00-f3a2-11e9-97f0-55185aea7e8f.png)
line-height мелковат

2019-10-20 22:38 UTC, fromanywhere commented on style.css
> +.todos-panel-list-task__view:hover > .todos-panel__button-clear,
`>` избыточен

2019-10-20 22:38 UTC, fromanywhere commented on style.css
> +
Теперь нужно сконцентрироваться на поближе к макету. Примерно везде потерялись отступы, элементы липнут друг к другу

2019-10-22 15:37 UTC, fromanywhere requested changes

2019-10-22 15:37 UTC, fromanywhere commented on style.css
> +  position: relative;
Последний рывок

Тень легла не туда 
![image](https://user-images.githubusercontent.com/1042969/67302646-dd661680-f4f9-11e9-8610-7fc286a1841c.png)

предлагается position: absolute; top: calc(100% + 5px); left: 1% и тогда еще на .todos-panel position: relative

2019-10-22 15:37 UTC, fromanywhere commented on style.css
> +  border-bottom: 2px solid #f2f2f2;
По макету там разделители все однопиксельные, что здесь, что в .todos-panel-list__task. А в .actions-bar вообще тогда убрать можно будет

2019-10-22 15:37 UTC, fromanywhere commented on style.css
> +.todos-panel-button__checkall:focus {
Вам бордеры эти на фокус только мешают сейчас — из-за увеличения ширины обводки оно прыгает. В макете они не прорисованы, а браузер сам рисует дефолтный outline. Предлагается убрать — меньше кода, меньше багов

2019-10-22 15:37 UTC, fromanywhere commented on style.css
> +.todos-panel-button__checkall:focus {
Здесь тоже бордер не нужен на самом деле

2019-10-22 15:37 UTC, fromanywhere commented on style.css
> +  border: 2px solid #cccccc;
и здесь

2019-10-22 15:37 UTC, fromanywhere commented on style.css
> +  width: 50px;
Когда текста много, иконку зажимает. flex-shrink: 0; спасет

2019-10-22 15:40 UTC, stasmilke commented on style.css
> +  position: relative;
Кстати в chrome тень легла неправильно (как на картинке), а в firefox как ожидалось.

2019-10-22 16:15 UTC, fromanywhere commented on style.css
> +  position: relative;
Safari и IE не согласны, а ведь это я взял самые последние, «лояльные» версии. Да и идеологически абсолют там лучше

2019-10-23 03:55 UTC, fromanywhere approved these changes

2019-10-23 11:29 UTC, merged